### ISSUE TITLE
Supervisor install fails when provisioning the box

### ISSUE THREAD

**Issue by JordanAssayah** [liip/drifter#100]
Error when installing supervisorctl when provisioning the box 

**Reproduction Steps:**

1. Type `$ vagrant provision` type `enter` and wait until supervisor task fails

**Expected behavior:**

When doing a `vagrant provision`, the supervisor install task is done with success

**Observed behavior:**

Error message : 
```
TASK: [supervisor | install config] ******************************************* 
failed: [default] => {"failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/supervisor/supervisord.conf", "size": 1180, "state": "file", "uid": 0}
msg: refusing to convert between file and link for /etc/supervisor/supervisord.conf
```

**Drifter version:** v1.0.2
**Vagrant version:** v1.8.5
**OS and version:** Ubuntu / 14.04 LTS
**Configuration files:**

`virtualization/playbook.yml`:
```
---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the rawbot-virtualization README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  sudo: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }

    ## Database, choose either mysql or postgres, some subsequent roles will be configured
    ## depending on your choice here.
    - { role: mysql }

    ## Scripting / Language support
    - { role: php-apache }    # PHP using Apache and mod-php

    ## Install Composer in the box
    - { role: composer }

    # Install NodeJS (for Gulp & co.)
    - { role: nodejs }

    # Install Solr in the box
    - { role: solr }

  tasks:
    - name: ensure php5-apcu and php5-xsl are installed
      apt: pkg={{ item }} state=present
      sudo: yes
      with_items:
        - php5-apcu
        - php5-xsl
      notify: restart apache

    - name: Copy the secret file
      shell: cp -n /vagrant/conf/secrets.yml.dist /vagrant/conf/secrets.yml

    - name: Set the correct server timezone
      shell: ln -sf /usr/share/zoneinfo/Europe/Zurich /etc/localtime
      sudo: yes

    - name: Restart mysql
      service: name=mysql state=restarted
      sudo: yes

    - name: Install Gulp globally
      shell: npm install -g gulp
      sudo: yes

    - name: install composer depedencies
      shell: cd /vagrant/; composer install

    - name: NPM Install
      shell: cd /vagrant/; npm install

    - name: Create cache folder
      file: path=/vagrant/cache state=directory mode=0777

    - name: mysql reset
      shell: php /vagrant/console mysql:reset
      args:
        chdir: /vagrant

    - name: Add codeception alias in bashrc aliases
      lineinfile: dest=/home/vagrant/.aliases line="alias codecept='/vagrant/vendor/bin/codecept'"
```
`virtualization/parameters.yml`: 
```
---
# Name of your project, will also be the vagrant box name
project_name: "zebra"

# Main hostname through which the vagrant box will be accessible
hostname: "zebra.lo"
# Alternative hostnames through which you want to access the vagrant box
hostnames: []

# The box IP, this must be unique across all your virtualized projects to
# avoid collisions. WARNING, this parameter will not guarantee that your box
# will be accessible at this IP depending on your network configuration or
# provider choice.
box_ip: "172.82.82.82"

# Name of the database to create for your project if you include the
# MySQL or PostgreSQL role
database_name: "zebra"

# Root directory of your project for the webserver and other purposes
root_directory: "/vagrant/www/"

php_version: "5.6"

solr_version: "5.5.1"
solr_config_dir: "/vagrant/conf/solr/"
```

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Drifter: Yes
* Problem happens to my colleagues aswell or only me: Yes
