### ISSUE TITLE
Error while installing DotDeb key for PHP

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/drifter#130]
Using the default box, provisioning fail during this task.

```
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "error getting key id from url: http://www.dotdeb.org/dotdeb.gpg", "traceback": "Traceback (most recent call last):\n  File \"/tmp/ansible_KyCvRX/ansible_module_apt_key.py\", line 165, in download_key\n    return rsp.read()\n  File \"/usr/lib/python2.7/socket.py\", line 351, in read\n    data = self._sock.recv(rbufsize)\n  File \"/usr/lib/python2.7/httplib.py\", line 573, in read\n    s = self.fp.read(amt)\n  File \"/usr/lib/python2.7/socket.py\", line 380, in read\n    data = self._sock.recv(left)\nerror: [Errno 104] Connection reset by peer\n"}
```

**Drifter version:** 1.0.8
**Vagrant version:** 1.8.6
**OS and version:** MacOS El Capitan 10.11.6

**Configuration files:**

```
- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    - { role: base }
    - { role: git }
    - { role: mysql }
    - { role: php-fpm }
    - { role: composer }
```

```
project_name: "hlm"
hostname: "hlm.lo"
hostnames: []
forwarded_ports: {
    "80": "8080",    # HTTP
    "443": "8443",   # HTTPS
    "3000": "3000",  # BrowserSync default port
}
database_name: "hlm"
root_directory: "/vagrant/"
php_version: 7.0
```

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Drifter: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- Problem happens to my colleagues aswell or only me: Yes, @rsnts 

Worked fine if switched to the following box:

```
box_name: "drifter/trusty64-php7"
box_url: "https://vagrantbox-public.liip.ch/drifter-trusty64-php7.json"
```
