### ISSUE TITLE
Role nodejs fails

### ISSUE THREAD

**Issue by ghn** [liip/drifter#248]
Using a fresh box with role "nodejs" leads to this error while provisioning:

```
TASK [nodejs : Install npm packages] *******************************************
ERROR! the field 'hosts' is required but was not set
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Drifter version:** v1.7.0 and commit 46d4a9d (master)
**Vagrant version:** 2.2.2
**OS and version:** osx 10.14.2

**Configuration files:**

*playbook.yml*

```
- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    - { role: base }
    - { role: git }
    - { role: postgresql }
    - { role: ssh }
    - { role: ruby }
    - { role: nodejs, nodejs_with_yarn: true }
```

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Drifter: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens to my colleagues aswell or only me: not tested
